# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(14151A)
$foreground = rgb(C5EEF8)
$color0 = rgb(3B3C41)
$color1 = rgb(081020)
$color2 = rgb(0A1327)
$color3 = rgb(1C3476)
$color4 = rgb(224093)
$color5 = rgb(A65F9E)
$color6 = rgb(439AB0)
$color7 = rgb(A4DEEC)
$color8 = rgb(729BA5)
$color9 = rgb(0B152A)
$color10 = rgb(0D1934)
$color11 = rgb(25459E)
$color12 = rgb(2E56C4)
$color13 = rgb(DD7FD3)
$color14 = rgb(59CEEA)
$color15 = rgb(A4DEEC)
