# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(15151A)
$foreground = rgb(DEEEF7)
$color0 = rgb(3C3C42)
$color1 = rgb(355279)
$color2 = rgb(355279)
$color3 = rgb(355279)
$color4 = rgb(355279)
$color5 = rgb(92327C)
$color6 = rgb(799BAE)
$color7 = rgb(C8DFEB)
$color8 = rgb(8C9CA5)
$color9 = rgb(476EA1)
$color10 = rgb(476EA1)
$color11 = rgb(476EA1)
$color12 = rgb(476EA1)
$color13 = rgb(C342A6)
$color14 = rgb(A1CFE8)
$color15 = rgb(C8DFEB)
